### ISSUE TITLE
set command in which-key not work

### ISSUE THREAD

**Issue by HIDE-r** [tenxsoydev/tabs-vs-spaces.nvim#5]
I can use this plugin normally by manually running command.

But when I set cmd on which-key plugin, it only can convert the current buffer all indent, can not use for range and still in visual mode.

[Kooha-2023-08-11-01-31-21.webm](https://github.com/tenxsoydev/tabs-vs-spaces.nvim/assets/51672711/a1a93f50-09d6-4fc1-be47-5cf53e1ba1a2)

```lua
wk.register({
...
...
	i = {
		name = "indent",
		t = { "<cmd>TabsVsSpacesConvert spaces_to_tabs<cr>"	, "space to tab"},
		s = { "<cmd>TabsVsSpacesConvert tabs_to_spaces<cr>"	, "tab to space"},
	},
}, { 
	prefix = "<leader>",
	mode = {"n", "v"}
})
```

but follow command in which key can work:
```lua
wk.register({
...
...
	i = {
		name = "indent",
		t = { "<cmd>'<,'>TabsVsSpacesConvert spaces_to_tabs<cr>"	, "space to tab"},
		s = { "<cmd>'<,'>TabsVsSpacesConvert tabs_to_spaces<cr>"	, "tab to space"},
}, { 
	prefix = "<leader>",
	mode = {"n", "v"}
})
```

it should be worked in the first method (I think it should be).

**Comment by ttytm** [comment]
Thanks for the report. Sorry about taking forever to reply.

This is as documented:
> ![Screenshot_20240618_111256](https://github.com/tenxsoydev/tabs-vs-spaces.nvim/assets/34311583/38e0272c-3a9e-4b70-8072-7393fdb0b083)

This is intended behavior, as the visual marks are what you automatically get when you start entering a command `:` with a range selected. Without the visual selection marks, it should target the entire buffer.
